backend:
  name: git-gateway
  branch: main

media_folder: "Static/Images"
public_folder: "/Static/Images"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price (₦)", name: "price", widget: "string" }
      - { label: "Category", name: "cat", widget: "select", options: ["Wigs","Shoes","Bags"] }
      - { label: "Image", name: "img", widget: "image" }
